### ISSUE TITLE
ReferenceError: Document is not defined

### ISSUE THREAD

**Issue by adam-s** [react-component/drawer#2]
I'm getting an error that `document` is not defined. I did a [ReferenceError: Document is not defined React](https://stackoverflow.com/questions/35068451/reactjs-document-is-not-defined) search and it seems that `document` doesn't exist when rendered on the server. I'm using a plain instance of [Apollo Universal Starter Kit](https://github.com/sysgears/apollo-universal-starter-kit). 

backend error { ReferenceError: document is not defined
    at Drawer._this.setLevelDomTransform (/home/adam/PhpstormProjects/joboty-admin/node_modules/rc-drawer-menu/lib/Drawer.js:215:9)
    at Drawer._this.getChildToRender (/home/adam/PhpstormProjects/joboty-admin/node_modules/rc-drawer-menu/lib/Drawer.js:247:15)
    at Drawer.render (/home/adam/PhpstormProjects/joboty-admin/node_modules/rc-drawer-menu/lib/Drawer.js:353:27)
    at walkTree (/home/adam/PhpstormProjects/joboty-admin/node_modules/react-apollo/getDataFromTree.js:36:32)
    at walkTree (/home/adam/PhpstormProjects/joboty-admin/node_modules/react-apollo/getDataFromTree.js:50:17)
    at /home/adam/PhpstormProjects/joboty-admin/node_modules/react-apollo/getDataFromTree.js:61:21
    at forEachSingleChild (/home/adam/PhpstormProjects/joboty-admin/node_modules/react/cjs/react.development.js:858:8)
    at traverseAllChildrenImpl (/home/adam/PhpstormProjects/joboty-admin/node_modules/react/cjs/react.development.js:762:5)
    at traverseAllChildrenImpl (/home/adam/PhpstormProjects/joboty-admin/node_modules/react/cjs/react.development.js:778:23)
    at traverseAllChildren (/home/adam/PhpstormProjects/joboty-admin/node_modules/react/cjs/react.development.js:833:10)
    at Object.forEachChildren [as forEach] (/home/adam/PhpstormProjects/joboty-admin/node_modules/react/cjs/react.development.js:878:3)
    at walkTree (/home/adam/PhpstormProjects/joboty-admin/node_modules/react-apollo/getDataFromTree.js:59:22)
    at walkTree (/home/adam/PhpstormProjects/joboty-admin/node_modules/react-apollo/getDataFromTree.js:50:17)
    at walkTree (/home/adam/PhpstormProjects/joboty-admin/node_modules/react-apollo/getDataFromTree.js:50:17)
    at walkTree (/home/adam/PhpstormProjects/joboty-admin/node_modules/react-apollo/getDataFromTree.js:50:17)
    at walkTree (/home/adam/PhpstormProjects/joboty-admin/node_modules/react-apollo/getDataFromTree.js:50:17) queryErrors: [ [Circular] ] }

**Comment by jljsj33** [comment]
0.5.4
