### ISSUE TITLE
Error with server side rendered application in next.js framework

### ISSUE THREAD

**Issue by nevestuan** [react-component/drawer#93]
I am getting this error **window is not defined**. I use Antd and Next.js framework with server side rendering. the window object is undefined when rendering at the server side.

(node:3627) UnhandledPromiseRejectionWarning: ReferenceError: window is not defined
    at Object.<anonymous> (/var/app/current/node_modules/rc-drawer/lib/Drawer.js:60:17)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/var/app/current/node_modules/rc-drawer/lib/index.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:688:30)

**Comment by jljsj33** [comment]
fix 1.8.3
